version: '2'
services:
    pocjedibkegateway2-app:
        image: pocjedibkegateway2
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pocjedibkegateway2-mysql:3306/pocjedibkegateway2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9999:9999
    pocjedibkegateway2-mysql:
        extends:
            file: mysql.yml
            service: pocjedibkegateway2-mysql
